services:
  vaultwarden:
    container_name: vaultwarden
    image: vaultwarden/server:latest
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./vw-data:/data
    environment:
      # Set to false after your 20 employees join
      - SIGNUPS_ALLOWED=true
      # Access /admin to manage users
      #- ADMIN_TOKEN=change_this_to_a_long_random_string 
    networks:
      - proxy-net
    labels:
      - autoxpose.enable=auto # or 'auto' for automatic exposure
      - autoxpose.subdomain=vaultwrden

networks:
  proxy-net:
    external: true
