name: SITE-Docker

networks:
  proxy-net:
    name: proxy-net
    driver: bridge
  tunnel-net:
    name: tunnel-net
    driver: bridge

include:
  # --- Network ---
  - network/compose.yml

  # --- Homepage ---
  - home/compose.yml

  # --- Wiki ---
  - apps/bookstack/compose.yml

  # --- Other Apps ---
  - apps/speedtest/compose.yml
  #- path: ${APPS_PATH:?err}/twenty/compose.yml
  - apps/beszel/compose.yml
