services:
  beszel:
    container_name: beszel
    image: henrygd/beszel
    restart: unless-stopped
    ports:
      - 8090:8090
    volumes:
      - ./data/beszel_data:/beszel_data
    environment:
      - APP_URL=https://beszel.${DOMAIN}
    env_file:
      - ../../.env
    labels:
      - autoxpose.enable=true # or 'auto' for automatic exposure
    healthcheck:
      # Calls the binary directly (no shell required)
      test: [ "CMD", "/beszel", "health", "--url", "http://localhost:8090" ]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 20s

  beszel-agent:
    container_name: beszel-agent
    image: henrygd/beszel-agent
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./data/beszel_agent_data:/var/lib/beszel-agent
      # monitor other disks / partitions by mounting a folder in /extra-filesystems
      # - /mnt/disk/.beszel:/extra-filesystems/sda1:ro
    environment:
      LISTEN: 45876
      KEY: ${API_KEY_BESZEL}
      TOKEN: 1f440fd2-462f-4dba-902e-5e7e5638fb40
      HUB_URL: https://beszel.${DOMAIN}
    env_file:
      - ../../.env
    healthcheck:
      # Calls the agent binary directly
      test: [ "CMD", "/agent", "health" ]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 15s
    cap_add:
      - SYS_RAWIO
      - SYS_ADMIN
    network_mode: host
