name: Deploy SITE-docker

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # 1. Connect the GitHub Runner to your Tailnet
      - name: Tailscale
        uses: tailscale/github-action@v4
        with:
          authkey: ${{ secrets.TAILSCALE_AUTHKEY}}
          statedir: /tmp/tailscale
          tags: tag:github-runner
          ping: 100.123.210.84

      # 2. Deploy via SSH using the Tailscale IP
      - name: Deploy to Server via SSH
        uses: appleboy/ssh-action@v1.2.5
        with:
          host: 100.123.210.84 # Your Tailscale IP
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          timeout: 60s
          script: |
            cd docker/SITE-docker
            echo "Deploying SITE-docker..."
            # 1. Pull the latest code from GitHub
            git pull origin main

            # 2. Pull new images and restart updated services
            # --quiet-pull keeps the logs clean
            docker compose pull
            docker compose up -d --remove-orphans

            # 3. Prune the system to reclaim space
            # -f (force) skips the "Are you sure?" prompt
            docker system prune -f
            cd
            echo "$(date) - A sever Push has been detected and compose files should have been updated." >> log.txt
